language: scala

sudo: required

services:
  - docker

scala:
  - 2.11.8

jdk:
  - openjdk8

branches:
  only:
    - master
    - staging
    - develop
    - /^v[0-9]+.[0-9]+.[0-9]+$/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_install:
  - umask 0022
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage testForBuild coverageReport coverageAggregate codacyCoverage

deploy:
  provider: script
  script: scripts/deploy/deploy-people-api-rest.sh
  skip_cleanup: true
  on:
    condition: $TRAVIS_PULL_REQUEST = false
    all_branches: true

notifications:
  slack: <hash>
  email:
    recipients:
      - <email>
    on_success: always
    on_failure: always